//priority: 0
const samples = [
	'amethyst',
	'bismuthinite',
	'bituminous_coal',
	'borax',
	'cassiterite',
	'cinnabar',
	'copper',
	'cryolite',
	'diamond_sample',
	'emerald_sample',
	'garnierite',
	'golds',		// This is correct, it is defined as such in the mod unfortunately
	'graphite',
	'gypsum',
	'halite',
	'hematite',
	'kaolinite',
	'lapislazuli',
	'lignite',
	'limonite',
	'magnetite',
	'malachite',
	'saltpeter',
	'silver',
	'sphalerite',
	'sulfur',
	'sylvite',
	'tetrahedrite',
	'vulcanic_sulfur'
]
const UnbreakBlock = [
	'minecraft:oak_log',
	'minecraft:oak_wood',
	'minecraft:stripped_oak_log',
	'minecraft:stripped_oak_wood',
	'minecraft:oak_planks',
	'minecraft:oak_stairs',
	'minecraft:oak_slab',
	'minecraft:oak_fence',
	'minecraft:oak_fence_gate',
	'minecraft:oak_door',
	'minecraft:oak_trapdoor',
	'minecraft:oak_pressure_plate',
	'minecraft:oak_button',

	'minecraft:spruce_log',
	'minecraft:spruce_wood',
	'minecraft:stripped_spruce_log',
	'minecraft:stripped_spruce_wood',
	'minecraft:spruce_planks',
	'minecraft:spruce_stairs',
	'minecraft:spruce_slab',
	'minecraft:spruce_fence',
	'minecraft:spruce_fence_gate',
	'minecraft:spruce_door',
	'minecraft:spruce_trapdoor',
	'minecraft:spruce_pressure_plate',
	'minecraft:spruce_button',
	
	'minecraft:birch_log',
	'minecraft:birch_wood',
	'minecraft:stripped_birch_log',
	'minecraft:stripped_birch_wood',
	'minecraft:birch_planks',
	'minecraft:birch_stairs',
	'minecraft:birch_slab',
	'minecraft:birch_fence',
	'minecraft:birch_fence_gate',
	'minecraft:birch_door',
	'minecraft:birch_trapdoor',
	'minecraft:birch_pressure_plate',
	'minecraft:birch_button',


	'minecraft:jungle_log',
	'minecraft:jungle_wood',
	'minecraft:stripped_jungle_log',
	'minecraft:stripped_jungle_wood',
	'minecraft:jungle_planks',
	'minecraft:jungle_stairs',
	'minecraft:jungle_slab',
	'minecraft:jungle_fence',
	'minecraft:jungle_fence_gate',
	'minecraft:jungle_door',
	'minecraft:jungle_trapdoor',
	'minecraft:jungle_pressure_plate',
	'minecraft:jungle_button',

	'minecraft:acacia_log',
	'minecraft:acacia_wood',
	'minecraft:stripped_acacia_log',
	'minecraft:stripped_acacia_wood',
	'minecraft:acacia_planks',
	'minecraft:acacia_stairs',
	'minecraft:acacia_slab',
	'minecraft:acacia_fence',
	'minecraft:acacia_fence_gate',
	'minecraft:acacia_door',
	'minecraft:acacia_trapdoor',
	'minecraft:acacia_pressure_plate',
	'minecraft:acacia_button',

	'minecraft:dark_oak_log',
	'minecraft:dark_oak_wood',
	'minecraft:stripped_dark_oak_log',
	'minecraft:stripped_dark_oak_wood',
	'minecraft:dark_oak_planks',
	'minecraft:dark_oak_stairs',
	'minecraft:dark_oak_slab',
	'minecraft:dark_oak_fence',
	'minecraft:dark_oak_fence_gate',
	'minecraft:dark_oak_door',
	'minecraft:dark_oak_trapdoor',
	'minecraft:dark_oak_pressure_plate',
	'minecraft:dark_oak_button',

	'minecraft:mangrove_log',
	'minecraft:mangrove_wood',
	'minecraft:stripped_mangrove_log',
	'minecraft:stripped_mangrove_wood',
	'minecraft:mangrove_planks',
	'minecraft:mangrove_stairs',
	'minecraft:mangrove_slab',
	'minecraft:mangrove_fence',
	'minecraft:mangrove_fence_gate',
	'minecraft:mangrove_door',
	'minecraft:mangrove_trapdoor',
	'minecraft:mangrove_pressure_plate',
	'minecraft:mangrove_button',

	'minecraft:cherry_log',
	'minecraft:cherry_wood',
	'minecraft:stripped_cherry_log',
	'minecraft:stripped_cherry_wood',
	'minecraft:cherry_planks',
	'minecraft:cherry_stairs',
	'minecraft:cherry_slab',
	'minecraft:cherry_fence',
	'minecraft:cherry_fence_gate',
	'minecraft:cherry_door',
	'minecraft:cherry_trapdoor',
	'minecraft:cherry_pressure_plate',
	'minecraft:cherry_button',

	'minecraft:crimson_stem',
	'minecraft:crimson_hyphae',
	'minecraft:stripped_crimson_stem',
	'minecraft:stripped_crimson_hyphae',
	'minecraft:crimson_planks',
	'minecraft:crimson_stairs',
	'minecraft:crimson_slab',
	'minecraft:crimson_fence',
	'minecraft:crimson_fence_gate',
	'minecraft:crimson_door',
	'minecraft:crimson_trapdoor',
	'minecraft:crimson_pressure_plate',
	'minecraft:crimson_button',
	
	'minecraft:warped_stem',
	'minecraft:warped_hyphae',
	'minecraft:stripped_warped_stem',
	'minecraft:stripped_warped_hyphae',
	'minecraft:warped_planks',
	'minecraft:warped_stairs',
	'minecraft:warped_slab',
	'minecraft:warped_fence',
	'minecraft:warped_fence_gate',
	'minecraft:warped_door',
	'minecraft:warped_trapdoor',
	'minecraft:warped_pressure_plate',
	'minecraft:warped_button',
	
	'minecraft:stone',
	'minecraft:stone_stairs',
	'minecraft:stone_slab',
	'minecraft:stone_pressure_plate',
	'minecraft:stone_button',
	'minecraft:cobblestone',
	'minecraft:cobblestone_stairs',
	'minecraft:cobblestone_slab',
	'minecraft:cobblestone_wall',
	'minecraft:mossy_cobblestone',
	'minecraft:mossy_cobblestone_stairs',
	'minecraft:mossy_cobblestone_slab',
	'minecraft:mossy_cobblestone_wall',
	'minecraft:smooth_stone',
	'minecraft:smooth_stone_slab',
	'minecraft:stone_bricks',
	'minecraft:stone_brick_stairs',
	'minecraft:stone_brick_slab',
	'minecraft:stone_brick_wall',
	'minecraft:mossy_stone_bricks',
	'minecraft:mossy_stone_brick_stairs',
	'minecraft:mossy_stone_brick_slab',
	'minecraft:mossy_stone_brick_wall',
	'minecraft:chiesled_stone_bricks',
	'minecraft:cracked_stone_bricks',

	'minecraft:granite',
	'minecraft:granite_stairs',
	'minecraft:granite_slab',
	'minecraft:granite_wall',
	'minecraft:polished_granite',
	'minecraft:polished_granite_stairs',
	'minecraft:polished_granite_slab',

	'minecraft:diorite',
	'minecraft:diorite_stairs',
	'minecraft:diorite_slab',
	'minecraft:diorite_wall',
	'minecraft:polished_diorite',
	'minecraft:polished_diorite_stairs',
	'minecraft:polished_diorite_slab',

	'minecraft:andesite',
	'minecraft:andesite_stairs',
	'minecraft:andesite_slab',
	'minecraft:andesite_wall',
	'minecraft:polished_andesite',
	'minecraft:polished_andesite_stairs',
	'minecraft:polished_andesite_slab',

	'minecraft:sandstone',
	'minecraft:sandstone_stairs',
	'minecraft:sandstone_slab',
	'minecraft:sandstone_wall',
	'minecraft:chisled_sandstone',
	'minecraft:smooth_sandstone',
	'minecraft:smooth_sandstone_stairs',
	'minecraft:smooth_sandstone_slab',
	'minecraft:cut_sandstone',
	'minecraft:cut_sandstone_slab',

	'minecraft:red_sandstone',
	'minecraft:red_sandstone_stairs',
	'minecraft:red_sandstone_slab',
	'minecraft:red_sandstone_wall',
	'minecraft:chisled_red_sandstone',
	'minecraft:smooth_red_sandstone',
	'minecraft:smooth_red_sandstone_stairs',
	'minecraft:smooth_red_sandstone_slab',
	'minecraft:cut_red_sandstone',
	'minecraft:cut_red_sandstone_slab',

	'minecraft:sea_lantern',
	'minecraft:prismarine',
	'minecraft:prismarine_stairs',
	'minecraft:prismarine_slab',
	'minecraft:prismarine_wall',
	'minecraft:prismarine_bricks',
	'minecraft:prismarine_bricks_stairs',
	'minecraft:prismarine_bricks_slab',
	'minecraft:dark_prismarine',
	'minecraft:dark_prismarine_stairs',
	'minecraft:dark_prismarine_slab',
]
const HalfUnbreakBlock = [
	'minecraft:spawner',
	'minecraft:nether_bricks',
	'minecraft:nether_brick_stairs',
	'minecraft:nether_brick_slab',
	'minecraft:nether_brick_wall',
	'minecraft:nether_brick_fence',
	'minecraft:cracked_nether_bricks',
	'minecraft:chiseled_nether_bricks',
	'minecraft:red_nether_bricks',
	'minecraft:red_nether_brick_stairs',
	'minecraft:red_nether_brick_slab',
	'minecraft:red_nether_brick_wall',	
	'minecraft:smooth_basalt',
	'minecraft:polished_basalt',	
	'minecraft:blackstone_stairs',
	'minecraft:blackstone_slab',
	'minecraft:blackstone_wall',
	'minecraft:chiseled_polished_blackstone',
	'minecraft:polished_blackstone',
	'minecraft:polished_blackstone_stairs',
	'minecraft:polished_blackstone_slab',
	'minecraft:polished_blackstone_wall',
	'minecraft:polished_blackstone_pressure_plate',
	'minecraft:polished_blackstone_button',
	'minecraft:polished_blackstone_bricks',
	'minecraft:cracked_polished_blackstone_bricks',
	'minecraft:polished_blackstone_brick_stairs',
	'minecraft:polished_blackstone_brick_slab',
	'minecraft:polished_blackstone_brick_wall',
	'minecraft:end_stone',
	'minecraft:end_stone_bricks',
	'minecraft:end_stone_bricks_stairs',
	'minecraft:end_stone_bricks_slab',
	'minecraft:end_stone_bricks_wall',
	'minecraft:purpur_block',
	'minecraft:purpur_pillar',
	'minecraft:purpur_stairs',
	'minecraft:purpur_slab',
	'minecraft:lantern',
	'minecraft:chain',
	'minecraft:cut_copper',
	'minecraft:cut_copper_stairs',
	'minecraft:cut_copper_slab',
	'minecraft:exposed_copper',
	'minecraft:exposed_cut_copper',
	'minecraft:exposed_cut_copper_stairs',
	'minecraft:exposed_cut_copper_slab',
	'minecraft:weathered_copper',
	'minecraft:weathered_cut_copper',
	'minecraft:weathered_cut_copper_stairs',
	'minecraft:weathered_cut_copper_slab',
	'minecraft:oxidized_copper',
	'minecraft:oxidized_cut_copper',
	'minecraft:oxidized_cut_copper_stairs',
	'minecraft:oxidized_cut_copper_slab',
	'minecraft:waxed_copper_block',
	'minecraft:waxed_cut_copper',
	'minecraft:waxed_cut_copper_stairs',
	'minecraft:waxed_cut_copper_slab',
	'minecraft:waxed_exposed_copper',
	'minecraft:waxed_exposed_cut_copper',
	'minecraft:waxed_exposed_cut_copper_stairs',
	'minecraft:waxed_exposed_cut_copper_slab',
	'minecraft:waxed_weathered_copper',
	'minecraft:waxed_weathered_cut_copper',
	'minecraft:waxed_weathered_cut_copper_stairs',
	'minecraft:waxed_weathered_cut_copper_slab',
	'minecraft:waxed_oxidized_copper',
	'minecraft:waxed_oxidized_cut_copper',
	'minecraft:waxed_oxidized_cut_copper_stairs',
	'minecraft:waxed_oxidized_cut_copper_slab',	
]
const TwiceHard = [
	'minecraft:netherrack',
	'minecraft:basalt',
	'minecraft:blackstone',
]
BlockEvents.modification(HTFC4 => {
	samples.forEach((name) => {
		HTFC4.modify('hardrock_samples:' + name, block => {
			block.destroySpeed = 0.95
		})
	});
})
BlockEvents.modification(e => {
	e.modify( UnbreakBlock , block => {
	  block.destroySpeed = 100000.0
	  block.explosionResistance = 100000.0
	})
})
BlockEvents.modification(e => {
	e.modify( HalfUnbreakBlock , block => {
	  block.destroySpeed = 500.0
	})
})
BlockEvents.modification(e => {
	e.modify( TwiceHard , block => {
	  block.destroySpeed = 3.0
	})
})