//priority: 10
ServerEvents.recipes(event => {
    // === remove mod =====================================================
    event.remove({input: ['#create:crushed_raw_materials'], type: 'create:splashing'})
    // ====replace item on crafting =======================================
	event.replaceInput({type: 'minecraft:crafting_shaped'}, 'create:zinc_ingot', '#forge:ingots/zinc')
	event.replaceInput({mod: 'copycats'}, '#forge:ingots/zinc', '#forge:sheets/zinc')
    // ====remove  id recipe ==============================================
    event.remove([
        //{id: 'create:deploying/cogwheel'},
		//{id: 'create:deploying/large_cogwheel'},
		{id: 'create:andesite_alloy'},
		{id: 'create:blasting/ingot_nickel_compat_immersiveengineering'},
		{id: 'create:blasting/ingot_silver_compat_immersiveengineering'},
		{id: 'create:blasting/zinc_ingot_from_crushed'},
		{id: 'create:crafting/appliances/dough'},
		{id: 'create:crafting/kinetics/fluid_pipe_vertical'},
		{id: 'create:crafting/materials/brass_ingot_from_compacting'},
		{id: 'create:crafting/materials/brass_ingot_from_decompacting'},
		{id: 'create:crafting/tree_fertilizer'},
		{id: 'create:crushing/asurine_recycling'},
		{id: 'create:crushing/asurine'},
		{id: 'create:crushing/blaze_rod'},
		{id: 'create:crushing/crimsite_recycling'},
		{id: 'create:crushing/crimsite'},
		{id: 'create:crushing/diamond_horse_armor'},
		{id: 'create:crushing/diorite_recycling'},
		{id: 'create:crushing/diorite'},
		{id: 'create:crushing/golden_horse_armor'},
		{id: 'create:crushing/gravel'},
		{id: 'create:crushing/iron_horse_armor'},
		{id: 'create:crushing/leather_horse_armor'},
		{id: 'create:crushing/ochrum_recycling'},
		{id: 'create:crushing/ochrum'},
		{id: 'create:crushing/tuff_recycling'},
		{id: 'create:crushing/tuff'},
		{id: 'create:crushing/veridium_recycling'},
		{id: 'create:crushing/veridium'},
		{id: 'create:milling/cobblestone'},
		{id: 'create:milling/gravel'},
		{id: 'create:milling/saddle'},
		{id: 'create:milling/sugar_cane'},
		{id: 'create:milling/wheat'},
		{id: 'create:mixing/chocolate_melting'},
		{id: 'create:mixing/lava_from_cobble'},
		{id: 'create:pressing/brass_ingot'},
		{id: 'create:pressing/copper_ingot'},
		{id: 'create:pressing/desh_ingot'},
		{id: 'create:pressing/calorite_ingot'},
		{id: 'create:pressing/ostrum_ingot'},
		{id: 'create:pressing/gold_ingot'},
		{id: 'create:pressing/iron_ingot'},
		{id: 'create:pressing/sugar_cane'},
		{id: 'create:smelting/ingot_nickel_compat_immersiveengineering'},
		{id: 'create:smelting/ingot_silver_compat_immersiveengineering'},
		{id: 'create:smelting/zinc_ingot_from_crushed'},
		{id: 'create:splashing/mekanism/crushed_raw_lead'},
		{id: 'create:splashing/mekanism/crushed_raw_uranium'},
		{id: 'create:splashing/wheat_flour'},
		//
		{id: 'create_sa:magma_cream_recipe'},
		//{id: 'create_sa:brass_cube_uncrafting'},
		//
		{id: 'createaddition:anvil/electrum'},
		{id: 'createaddition:compat/immersiveengineering/constantan'},
		{id: 'createaddition:compat/immersiveengineering/crushing/steel_ingot'},
		{id: 'createaddition:compat/immersiveengineering/electrum'},
		{id: 'createaddition:compat/immersiveengineering/fabric_sail'},
		{id: 'createaddition:compat/immersiveengineering/item_aplication/kiln_brick'},
		{id: 'createaddition:compat/tconstruct/hepatizon'},
		{id: 'createaddition:compat/tconstruct/manyullyn'},
		{id: 'createaddition:compat/tconstruct/queens_slime'},
		{id: 'createaddition:compat/tconstruct/rose_gold'},
		{id: 'createaddition:compat/tconstruct/slimesteel'},
		{id: 'createaddition:crafting/electrum_ingot'},
		{id: 'createaddition:mixing/electrum'},
		{id: 'createaddition:mixing/bioethanol'},
		{id: 'createaddition:pressing/aluminum_ingot'},
		{id: 'createaddition:pressing/brass_ingot'},
		{id: 'createaddition:pressing/constantan_ingot'},
		{id: 'createaddition:pressing/electrum_ingot'},
		{id: 'createaddition:pressing/electrum_plate'},
		{id: 'createaddition:pressing/lead_ingot'},
		{id: 'createaddition:pressing/uranium_ingot'},
		{id: 'createaddition:pressing/zinc_ingot'},
		{id: 'createaddition:rolling/aluminum_plate'},
		{id: 'createaddition:rolling/electrum_ingot'},
		{id: 'createaddition:rolling/lead_plate'},
		{id: 'createaddition:rolling/steel_plate'},
		//
		{id: 'vintageimprovements:osmium_ingot'},
		{id: 'vintageimprovements:curving/iron_sheet'},
		//
		{id: 'create_mechanical_extruder:extruding/limestone'},
		{id: 'create_mechanical_extruder:extruding/scoria'},
		//
		{id: 'createdieselgenerators:basin_fermenting/dough'},
		{id: 'createdieselgenerators:compacting/plant_oil'},
		{id: 'createdieselgenerators:crafting/asphalt_block'},
		{id: 'createdieselgenerators:crafting/asphalt_stairs'},
		{id: 'createdieselgenerators:crafting/asphalt_slab'},
		{id: 'createdieselgenerators:mixing/asphalt_block'},
		{id: 'createdieselgenerators:mixing/biodiesel'},
		//
		{id: 'create_hc:gear_small'},
		{id: 'create_hc:gear_large'},
		//
		{id: 'createbigcannons:gunpowder_pinch'},
		{id: 'createbigcannons:gunpowder_from_pinches'},
		{id: 'createbigcannons:melting/melt_bronze_block'},
		{id: 'createbigcannons:melting/melt_bronze_ingot'},
		{id: 'createbigcannons:melting/melt_bronze_nugget'},
		{id: 'createbigcannons:melting/melt_cast_iron_ingot'},
		{id: 'createbigcannons:melting/melt_cast_iron_block'},
		{id: 'createbigcannons:melting/melt_cast_iron_nugget'},
		{id: 'createbigcannons:melting/melt_steel_block'},
		{id: 'createbigcannons:melting/melt_steel_nugget'},
		{id: 'createbigcannons:melting/melt_steel_ingot'},
		{id: 'createbigcannons:mixing/alloy_nethersteel_cast_iron'},
		{id: 'createbigcannons:mixing/alloy_nethersteel_steel'},
		{id: 'createbigcannons:alloy/nethersteel_cast_iron'},
		{id: 'createbigcannons:alloy/nethersteel_steel'},
		{id: 'createbigcannons:compacting/forge_nethersteel_nugget'},
		{id: 'createbigcannons:compacting/forge_nethersteel_ingot'},
		//
		{id: `/^createlowheated:mixing/.*/`},
		//
		{id: 'createsifter:sifting/dirt_strig_mesh_waterlogged'},
		{id: 'createsifter:sifting/gravel_advanced_brass_mesh'},
		{id: 'createsifter:sifting/gravel_andesite_mesh'},
		{id: 'createsifter:sifting/gravel_brass_mesh'},
		{id: 'createsifter:sifting/gravel_zinc_mesh'},
		{id: 'createsifter:sifting/sand_andesite_mesh'},
		{id: 'createsifter:sifting/sand_brass_mesh'},
		{id: 'createsifter:sifting/sand_string_mesh'},
		{id: 'createsifter:sifting/sand_zinc_mesh'},
		//
		{id: 'createmetallurgy:alloying/steel'},
		{id: 'createmetallurgy:sequenced_assembly/steel_track'},
		{id: 'createmetallurgy:blasting/coke_from_coal'},
		{id: 'createmetallurgy:casting_in_basin/andesite_alloy_from_iron'},
		{id: 'createmetallurgy:casting_in_basin/andesite_alloy_from_zinc'},
		{id: 'createmetallurgy:casting_in_table/aluminum/plate'},
		{id: 'createmetallurgy:casting_in_table/aluminum/rod'},
		{id: 'createmetallurgy:casting_in_table/brass/plate'},
		{id: 'createmetallurgy:casting_in_table/brass/rod'},
		{id: 'createmetallurgy:casting_in_table/bronze/plate'},
		{id: 'createmetallurgy:casting_in_table/bronze/rod'},
		{id: 'createmetallurgy:casting_in_table/constantan/plate'},
		{id: 'createmetallurgy:casting_in_table/constantan/rod'},
		{id: 'createmetallurgy:casting_in_table/copper/plate'},
		{id: 'createmetallurgy:casting_in_table/copper/rod'},
		{id: 'createmetallurgy:casting_in_table/electrum/plate'},
		{id: 'createmetallurgy:casting_in_table/electrum/rod'},
		{id: 'createmetallurgy:casting_in_table/gold/plate'},
		{id: 'createmetallurgy:casting_in_table/gold/rod'},
		{id: 'createmetallurgy:casting_in_table/invar/plate'},
		{id: 'createmetallurgy:casting_in_table/invar/rod'},
		{id: 'createmetallurgy:casting_in_table/iron/plate'},
		{id: 'createmetallurgy:casting_in_table/iron/rod'},
		{id: 'createmetallurgy:casting_in_table/lead/plate'},
		{id: 'createmetallurgy:casting_in_table/lead/rod'},
		{id: 'createmetallurgy:casting_in_table/netherite/plate'},
		{id: 'createmetallurgy:casting_in_table/netherite/rod'},
		{id: 'createmetallurgy:casting_in_table/nickel/plate'},
		{id: 'createmetallurgy:casting_in_table/nickel/rod'},
		{id: 'createmetallurgy:casting_in_table/osmium/plate'},
		{id: 'createmetallurgy:casting_in_table/osmium/rod'},
		{id: 'createmetallurgy:casting_in_table/silver/plate'},
		{id: 'createmetallurgy:casting_in_table/silver/rod'},
		{id: 'createmetallurgy:casting_in_table/steel/plate'},
		{id: 'createmetallurgy:casting_in_table/steel/rod'},
		{id: 'createmetallurgy:casting_in_table/tin/plate'},
		{id: 'createmetallurgy:casting_in_table/tin/rod'},
		{id: 'createmetallurgy:casting_in_table/tungsten/plate'},
		{id: 'createmetallurgy:casting_in_table/tungsten/rod'},
		{id: 'createmetallurgy:casting_in_table/zinc/plate'},
		{id: 'createmetallurgy:casting_in_table/zinc/rod'},
		//{id: 'create:crafting/kinetics/large_cogwheel_from_little'},
		//{id: 'create:crafting/kinetics/gearboxfrom_conversion'},
		//{id: 'create:crafting/kinetics/vertical_gearboxfrom_conversion'},		
	])
    // ==== remove all ===================================================
    event.remove({output: [
		//'create_hc:saw_blade',
		//'create_hc:drill_head',
        'create:bar_of_chocolate',
		'create:brass_ingot',
		'create:brass_sheet',
		'create:copper_sheet',
		'create:golden_sheet',
		'create:iron_sheet',
		'create:red_sand_paper',
		'create:zinc_ingot',
		'create:zinc_sheet',
		//
		'createbigcannons:cast_iron_ingot',
		'createbigcannons:cast_iron_nugget',
		'createbigcannons:cast_iron_block',
		'createbigcannons:spring_wire',
		'createbigcannons:basin_foundry_lid',
		//
		'create_hc:press_head',
		'create_hc:rope',
		'create_hc:shaft',
		//
		//'create_new_age:nuclear_fuel',
		//'create_new_age:radioactive_thorium',
		//'create_new_age:reactor_casing',
		//'create_new_age:reactor_fuel_acceptor',
		//'create_new_age:reactor_glass',
		//'create_new_age:reactor_heat_acceptor',
		//'create_new_age:reactor_heat_vent',
		//'create_new_age:reactor_rod',
		//'create_new_age:thorium',
		//
		'create_sa:block_picker',
		'create_sa:brass_axe',
		'create_sa:brass_hoe',
		'create_sa:brass_pickaxe',
		'create_sa:brass_shovel',
		'create_sa:brass_sword',
		'create_sa:copper_axe',
		'create_sa:copper_boots',
		'create_sa:copper_chestplate',
		'create_sa:copper_helmet',
		'create_sa:copper_hoe',
		'create_sa:copper_leggings',
		'create_sa:copper_magnet',
		'create_sa:copper_pickaxe',
		'create_sa:copper_shovel',
		'create_sa:copper_sword',
		'create_sa:zinc_axe',
		'create_sa:zinc_hoe',
		'create_sa:zinc_pickaxe',
		'create_sa:zinc_shovel',
		'create_sa:zinc_sword',
		//
		'createaddition:electrum_ingot',
		//
		'createmetallurgy:tungsten_block',
		'createmetallurgy:tungsten_ingot',
		'createmetallurgy:tungsten_sheet',
		'createmetallurgy:tungsten_nugget',
		'createmetallurgy:tungsten_wire',
		//
		'createnergy:silver_block',
		'createnergy:silver_ingot',
		//
		'createsifter:andesite_mesh',
		'createsifter:zinc_mesh'
	]})
})