//priority: 10
ServerEvents.recipes(event => {
    event.remove({output: ['#forge:sheets'], mod: 'tfc_ie_addon'})
	event.remove({output: ['#forge:plates'], mod: 'tfc_ie_addon'})
	event.remove({output: ['#forge:rods'], mod: 'tfc_ie_addon'})
    event.remove({output: ['#forge:sheets'], mod: 'immersiveengineering'})
	event.remove({output: ['#forge:plates'], mod: 'immersiveengineering'})
	event.remove({output: ['#forge:rods'], mod: 'immersiveengineering'})
	//event.remove({output: ['#forge:dyes'], mod: 'tfc_ie_addon'})
	//event.remove({output: ['#forge:dyes'], mod: 'mekanism'})
	event.remove({output: ['mekanism:bio_fuel'], type: 'mekanism:crushing'})
	event.remove({output: ['#forge:dusts'], type: 'immersiveengineering:hammer_crushing'})
	event.remove({output: ['#forge:wires'], type: 'immersiveengineering:metal_press'})
	event.remove({output: ['#forge:gears'], type: 'immersiveengineering:metal_press'})
	event.remove({output: ['#tfc:foods/flour'], type: 'immersiveengineering:crusher'})
	event.remove({output: ['#forge:storage_blocks'], type: 'immersiveengineering:metal_press'})
	// replace
	event.replaceInput({type: 'minecraft:crafting_shaped'}, 'immersiveengineering:lantern', 'tfc:metal/lamp/copper')
	event.replaceInput({type: 'minecraft:crafting_shaped'}, 'mekanism:dust_charcoal', 'tfc:powder/charcoal')
	event.replaceInput({mod: 'ad_astra'}, 'ad_astra:steel_rod', '#forge:rods/steel')
	event.replaceInput({mod: 'comforts'}, 'minecraft:white_wool', '#forge:cloth')
	event.replaceInput({mod: 'chiselsandbits'}, 'minecraft:smooth_stone_slab', '#forge:smooth_stone_slab')
	event.replaceInput({mod: 'securitycraft'}, 'minecraft:iron_ingot', '#forge:plates/iron')
	event.replaceInput({mod: 'railways'}, 'minecraft:campfire', 'tfc:torch')
	event.replaceInput({mod: 'dynamictrees'}, 'minecraft:dirt', '#forge:dirt')
	event.replaceInput({mod: 'pneumaticcraft'}, 'minecraft:glowstone', 'mekanismgenerators:solar_generator')
	event.replaceInput({mod: 'steam_powered'}, 'steam_powered:brass_ingot', 'tfc:metal/ingot/brass')
	event.replaceInput({mod: 'steam_powered'}, 'steam_powered:brass_sheet', 'tfc:metal/sheet/brass')
	event.replaceInput({mod: 'steam_powered'}, 'steam_powered:bronze_ingot', 'tfc:metal/ingot/bronze')
	event.replaceInput({mod: 'steam_powered'}, 'steam_powered:steel_ingot', 'tfc:metal/ingot/steel')
	event.replaceInput({mod: 'steam_powered'}, 'steam_powered:steel_sheet', 'tfc:metal/sheet/steel')
	event.replaceInput({mod: 'steam_powered'}, 'steam_powered:tin_ingot', 'tfc:metal/ingot/tin')
	event.replaceInput({mod: 'steam_powered'}, 'steam_powered:tin_cog_wheel', '#forge:gears/steel')
	event.replaceInput({mod: 'tfmg'}, 'tfmg:copper_cable', 'immersiveengineering:wirecoil_copper')
	event.replaceInput({mod: 'protection_pixel'}, 'minecraft:iron_chestplate', 'tfc:metal/chestplate/steel')
	event.replaceInput({mod: 'protection_pixel'}, 'minecraft:iron_leggings', 'tfc:metal/greaves/steel')
	event.replaceInput({mod: 'protection_pixel'}, 'minecraft:iron_helmet', 'adpother:iron_respirator')
	event.replaceInput({mod: 'adpother'}, '#minecraft:leaves', 'thinair:respirator')
	// shappeles recipe
	//event.shapeless('immersiveengineering:sawblade', ['create_hc:saw_blade'])
	// remove all recipes
	event.remove({output: [
		'ad_astra:compressor',
		'ad_astra:hammer',
		'ad_astra:iron_plate',
		'ad_astra:iron_rod',
		'ad_astra:steel_rod',
		'ad_astra:steel_block',
		'ad_astra:steel_ingot',
		'ad_astra:steel_plate',
		'ad_astra:steel_nugget',

		'butchersdelight:roaster',
		'butchersdelightfoods:cookedbeefribs',
		'butchersdelightfoods:cooked_leg_cow',
		'butchersdelightfoods:coockedbeeftenderloin',
		'butchersdelightfoods:cookedsheepshank',
		'butchersdelightfoods:cookedsheeprack',
		'butchersdelightfoods:cooked_sheeploin',
		'butchersdelightfoods:cooked_ham',
		'butchersdelightfoods:cookedporkloin',
		'butchersdelightfoods:cookedporkribs',
		'butchersdelightfoods:cooked_goat_shank',
		'butchersdelightfoods:cooked_goat_rack',
		'butchersdelightfoods:cooked_goat_loin',
		'butchersdelightfoods:cooked_llama_leg',
		'butchersdelightfoods:cooked_llama_ribs',
		'butchersdelightfoods:cooked_llama_loin',

		'chiselsandbits:chisel_stone',
		'chiselsandbits_tfc:chisel_head_stone',
		'chiselsandbits_tfc:chisel_head_iron',
		'chiselsandbits_tfc:chisel_head_gold',
		'chiselsandbits_tfc:chisel_head_diamond',
		'chiselsandbits_tfc:chisel_head_netherite',

		'htm:sawdust',
		'htm:plant_fiber',
		'htm:hammer_head',
		'htm:hammer',
		
		'immersiveengineering:pickaxe_steel',
		'immersiveengineering:shovel_steel',
		'immersiveengineering:axe_steel',
		'immersiveengineering:hoe_steel',
		'immersiveengineering:sword_steel',
		'immersiveengineering:armor_steel_feet',
		'immersiveengineering:armor_steel_legs',
		'immersiveengineering:armor_steel_chest',
		'immersiveengineering:armor_steel_head',
		'immersiveengineering:plate_silver',
		'immersiveengineering:plate_gold',
		'immersiveengineering:plate_aluminum',
		'immersiveengineering:plate_steel',
		'immersiveengineering:plate_copper',
		'immersiveengineering:plate_nickel',
		'immersiveengineering:plantoil',
		'immersiveengineering:ingot_silver',
		'immersiveengineering:ingot_nickel',
		'immersiveengineering:dust_steel',
		//'immersiveengineering:dust_wood',
		'immersiveengineering:stick_aluminum',
		'immersiveengineering:lantern',
		'immersiveengineering:wire_aluminum',
		'immersiveengineering:wire_copper',
		'immersiveengineering:wire_electrum',
		'immersiveengineering:wire_steel',
		'immersiveengineering:wire_lead',

		'immersivegeology:ingot_zinc',
		'immersivegeology:rod_zinc',
		'immersivegeology:plate_zinc',
		'immersivegeology:wire_zinc',
		'immersivegeology:wire_chromium',
		'immersivegeology:gear_aluminum',
		'immersivegeology:gear_bronze',
		'immersivegeology:gear_chromium',
		'immersivegeology:gear_copper',
		'immersivegeology:gear_gold',
		'immersivegeology:gear_iron',
		'immersivegeology:gear_lead',
		'immersivegeology:gear_nickel',
		'immersivegeology:gear_silver',
		'immersivegeology:gear_steel',
		'immersivegeology:gear_stainlesssteel',
		'immersivegeology:gear_tin',
		'immersivegeology:gear_uranium',
		'immersivegeology:gear_zinc',

		//'immersivepetroleum:asphalt',
		//'immersivepetroleum:asphalt_slab',
		//'immersivepetroleum:asphalt_stair',

		//'mekanism:sawdust',
		'mekanism:steel_block',
		'mekanism:steel_nugget',
		'mekanism:ingot_bronze',
		'mekanism:ingot_steel',
		'mekanism:ingot_tin',
		'mekanism:ingot_lead',
		'mekanism:ingot_uranium',
		'mekanism:precision_sawmill',
		'mekanism:cardboard_box',
		'mekanism:basic_sawing_factory',
		'mekanism:advanced_sawing_factory',
		'mekanism:elite_sawing_factory',
		'mekanism:ultimate_sawing_factory',
		'mekanism:nutritional_liquifier',

		//'mekanism:module_nutritional_injection_unit',
		//'railways:track_twilightforest_canopy',
		//'railways:track_twilightforest_darkwood',
		//'railways:track_twilightforest_mangrove',
		//'railways:track_twilightforest_minewood',
		//'railways:track_twilightforest_sortingwood',
		//'railways:track_twilightforest_timewood',
		//'railways:track_twilightforest_transwood',
		//'railways:track_twilightforest_twilight_oak',

		'sewingkit:stone_sewing_needle',
		'sewingkit:gold_sewing_needle',
		'sewingkit:diamond_sewing_needle',
		'sewingkit:netherite_sewing_needle',
		'sewingkit:wool_hat',
		'sewingkit:wool_shirt',
		'sewingkit:wool_pants',
		'sewingkit:wool_shoes',

		'spartanweaponry:stone_longsword',
		'spartanweaponry:stone_katana',
		'spartanweaponry:stone_saber',
		'spartanweaponry:stone_rapier',
		'spartanweaponry:stone_greatsword',
		'spartanweaponry:stone_glaive',
		'spartanweaponry:stone_scythe',
		'spartanweaponry:leather_heavy_crossbow',
		'spartanweaponry:wooden_heavy_crossbow',
		'spartanweaponry:wooden_dagger',
		'spartanweaponry:wooden_parrying_dagger',
		'spartanweaponry:wooden_longsword',
		'spartanweaponry:wooden_katana',
		'spartanweaponry:wooden_saber',
		'spartanweaponry:wooden_rapier',
		'spartanweaponry:wooden_greatsword',
		'spartanweaponry:wooden_battle_hammer',
		'spartanweaponry:wooden_warhammer',
		'spartanweaponry:wooden_spear',
		'spartanweaponry:wooden_halberd',
		'spartanweaponry:wooden_lance',
		'spartanweaponry:wooden_throwing_knife',
		'spartanweaponry:wooden_tomahawk',
		'spartanweaponry:wooden_battleaxe',
		'spartanweaponry:wooden_flanged_mace',
		'spartanweaponry:wooden_glaive',
		'spartanweaponry:wooden_scythe',

		'steam_powered:brass_sheet',
		'steam_powered:steel_sheet',

		'tinyredstone:silicon',
		'tinyredstone:silicon_compound',

		//'tfc:food/barley_dough',
		//'tfc:food/maize_dough',
		//'tfc:food/oat_dough',
		//'tfc:food/rice_dough',
		//'tfc:food/rye_dough',
		//'tfc:food/wheat_dough',
		
		'tfmg:asphalt',
		'tfmg:steel_block',
		'tfmg:aluminum_block',
		'tfmg:lead_block',
		'tfmg:nickel_block',
		'tfmg:coal_coke_block',
		'tfmg:lead_ore',
		'tfmg:deepslate_lead_ore',
		'tfmg:deepslate_nickel_ore',
		'tfmg:nickel_ingot',
		'tfmg:nickel_ore',
		'tfmg:lithium_ore',
		'tfmg:deepslate_lithium_ore',
		'tfmg:sulfur',
		'tfmg:lignite',
		'tfmg:aluminum_ingot',
		'tfmg:cast_iron_ingot',
		'tfmg:lead_ingot',
		'tfmg:coal_coke',
		'tfmg:heavy_plate',
		'tfmg:steel_ingot',
		'tfmg:lead_ingot',
		'tfmg:copper_wire',
		'tfmg:aluminum_wire',
		'tfmg:raw_lead',
		'tfmg:raw_nickel',
		'tfmg:steel_helmet',
		'tfmg:steel_chestplate',
		'tfmg:steel_leggings',
		'tfmg:steel_boots',
		'tfmg:copper_cable',
		'tfmg:steel_axe',
		'tfmg:steel_hoe',
		'tfmg:steel_shovel',
		'tfmg:steel_pickaxe',
		'tfmg:steel_sword',
		'tfmg:aluminum_axe',
		'tfmg:aluminum_hoe',
		'tfmg:aluminum_shovel',
		'tfmg:aluminum_pickaxe',
		'tfmg:aluminum_sword',
		'tfmg:lead_axe',
		'tfmg:lead_hoe',
		'tfmg:lead_shovel',
		'tfmg:lead_pickaxe',
		'tfmg:lead_sword',
		'tfmg:sulfur_dust',
		'tfmg:sulfur_dust',
		'tfmg:copper_coil',

		'twilightforest:uncrafting_table',

		//'waterstrainer:strainer_fisherman',

		//'untamedwilds:food_turtle_soup',
		//'untamedwilds:food_hemlock_stew',
		'untamedwilds:food_pemmican',

		//'waystones:sharestone',
		//'waystones:portstone',
		//'waystones:return_scroll',
		//'waystones:bound_scroll',
		//'waystones:warp_scroll',
		
		'vintageimprovements:sulfur',
		'vintageimprovements:sulfur_chunk',
		'vintageimprovements:sulfur_block',
		'vintageimprovements:aluminum_sheet',
		'vintageimprovements:bronze_sheet',
		'vintageimprovements:lead_sheet',
		'vintageimprovements:nickel_sheet',
		'vintageimprovements:aluminum_rod',
        'vintageimprovements:steel_rod',
        'vintageimprovements:tin_sheet',
        'vintageimprovements:cast_iron_sheet',
        'vintageimprovements:nickel_sheet',
        'vintageimprovements:zinc_rod',
		'vintageimprovements:zinc_sheet',
		'vintageimprovements:electrum_rod',
		'vintageimprovements:constantan_rod',
		'vintageimprovements:lead_rod',
		'vintageimprovements:uranium_rod',
        'vintageimprovements:silver_wire',
        'vintageimprovements:steel_wire',
	]})
	event.remove([
		{id: 'ad_astra:alloying/steel_ingot_from_alloying_iron_ingot_and_coals'},
		{id: 'ad_astra:hammering/calorite_plate'},
		{id: 'ad_astra:hammering/desh_plate'},
		{id: 'ad_astra:hammering/ostrum_plate'},
		{id: 'ad_astra:hammering/steel_plate'},
		{id: 'ad_astra:recipes/soul_torch'},

		{id: 'brewery:pork_knuckle'},
		{id: 'brewery:fried_chicken'},
		{id: 'brewery:half_chicken'},
		{id: 'brewery:sasague'},
		{id: 'brewery:mashed_potatoes'},
		{id: 'brewery:potato_salad'},
		{id: 'brewery:dumplings'},
		{id: 'brewery:pretzel'},
		{id: 'brewery:gingerbread'},

		{id: 'cold_sweat:hearth'},
		{id: 'cold_sweat:waterskin'},
		{id: 'cold_sweat:thermometer'},
		{id: 'cold_sweat:thermolith'},
		{id: 'cold_sweat:icebox'},
		{id: 'cold_sweat:boiler'},
		{id: 'cold_sweat:smokestack'},
		{id: 'cold_sweat:sewing_table'},

		{id: 'comforts:sleeping_bag_to_white'},
		{id: 'comforts:sleeping_bag_white'},
		{id: 'comforts:hammock_white'},

		{id: 'compressedcreativity:crafting/mechanical_visor_upgrade'},
		{id: 'compressedcreativity:mixing/brass_coated_upgrade_matrix'},
		{id: 'compressedcreativity:mixing/brass_gilded_lapis_lazuli'},
		{id: 'compressedcreativity:sequenced_assembly/mesh_splashing'},

		{id: 'coralstfc:barrel/coral_powder'},

		{id: 'firmaciv:quern/amethyst'},
		{id: 'firmaciv:quern/diamond'},
		{id: 'firmaciv:quern/emerald'},
		{id: 'firmaciv:quern/lapis_lazuli'},
		{id: 'firmaciv:quern/opal'},
		{id: 'firmaciv:quern/pyrite'},
		{id: 'firmaciv:quern/ruby'},
		{id: 'firmaciv:quern/sapphire'},
		{id: 'firmaciv:quern/topaz'},

		{id: 'htm:food/chicken'},
		{id: 'htm:weapon/arrow_metal'},
		{id: 'htm:compat/tfc/crafting/dried_kelp_block'},

		//{id: 'immersiveengineering:crafting/treated_wood_vertical_from_horizontal'},
		//{id: 'immersiveengineering:crafting/treated_wood_horizontal_to_slab'},
		//{id: 'immersiveengineering:crafting/stairs_treated_wood_horizontal'},
		//{id: 'immersiveengineering:crafting/wire_copper'},
		//{id: 'immersiveengineering:crafting/wire_electrum'},
		//{id: 'immersiveengineering:crafting/gunpowder_from_dusts'},
		{id: 'immersiveengineering:alloysmelter/brass'},
		{id: 'immersiveengineering:alloysmelter/bronze'},
		{id: 'immersiveengineering:alloysmelter/constantan'},
		{id: 'immersiveengineering:alloysmelter/electrum'},
		{id: 'immersiveengineering:alloysmelter/manyullyn'},
		{id: 'immersiveengineering:alloysmelter/rose_gold'},
		{id: 'immersiveengineering:arcfurnace/ore_aluminum'},
		{id: 'immersiveengineering:arcfurnace/ore_copper'},
		{id: 'immersiveengineering:arcfurnace/ore_gold'},
		{id: 'immersiveengineering:arcfurnace/ore_iron'},
		{id: 'immersiveengineering:arcfurnace/ore_lead'},
		{id: 'immersiveengineering:arcfurnace/ore_nickel'},
		{id: 'immersiveengineering:arcfurnace/ore_osmium'},
		{id: 'immersiveengineering:arcfurnace/ore_silver'},
		{id: 'immersiveengineering:arcfurnace/ore_tin'},
		{id: 'immersiveengineering:arcfurnace/ore_uranium'},
		{id: 'immersiveengineering:arcfurnace/ore_zinc'},
		{id: 'immersiveengineering:arcfurnace/raw_block_aluminum'},
		{id: 'immersiveengineering:arcfurnace/raw_block_copper'},
		{id: 'immersiveengineering:arcfurnace/raw_block_gold'},
		{id: 'immersiveengineering:arcfurnace/raw_block_iron'},
		{id: 'immersiveengineering:arcfurnace/raw_block_lead'},
		{id: 'immersiveengineering:arcfurnace/raw_block_nickel'},
		{id: 'immersiveengineering:arcfurnace/raw_block_osmium'},
		{id: 'immersiveengineering:arcfurnace/raw_block_silver'},
		{id: 'immersiveengineering:arcfurnace/raw_block_tin'},
		{id: 'immersiveengineering:arcfurnace/raw_block_uranium'},
		{id: 'immersiveengineering:arcfurnace/raw_block_zinc'},
		{id: 'immersiveengineering:arcfurnace/raw_ore_aluminum'},
		{id: 'immersiveengineering:arcfurnace/raw_ore_copper'},
		{id: 'immersiveengineering:arcfurnace/raw_ore_gold'},
		{id: 'immersiveengineering:arcfurnace/raw_ore_iron'},
		{id: 'immersiveengineering:arcfurnace/raw_ore_lead'},
		{id: 'immersiveengineering:arcfurnace/raw_ore_nickel'},
		{id: 'immersiveengineering:arcfurnace/raw_ore_osmium'},
		{id: 'immersiveengineering:arcfurnace/raw_ore_silver'},
		{id: 'immersiveengineering:arcfurnace/raw_ore_tin'},
		{id: 'immersiveengineering:arcfurnace/raw_ore_uranium'},
		{id: 'immersiveengineering:arcfurnace/raw_ore_zinc'},
		{id: 'immersiveengineering:blastfurnace/steel_block'},
		{id: 'immersiveengineering:blastfurnace/steel'},
		{id: 'immersiveengineering:blueprint/mold_packing_9'},
		{id: 'immersiveengineering:blueprint/mold_wire'},
		{id: 'immersiveengineering:cokeoven/coke_block'},
		{id: 'immersiveengineering:cokeoven/coke'},
		{id: 'immersiveengineering:crafting/constantan_mix'},
		{id: 'immersiveengineering:crafting/electrum_mix'},
		{id: 'immersiveengineering:crafting/concrete'},
		{id: 'immersiveengineering:crafting/concrete_to_slab'},
		{id: 'immersiveengineering:crafting/drillhead_iron'},
		{id: 'immersiveengineering:crafting/ersatz_leather'},
		{id: 'immersiveengineering:crafting/gunpowder_from_dusts'},
		{id: 'immersiveengineering:crafting/paper_from_sawdust'},
		{id: 'immersiveengineering:crafting/plate_iron_hammering'},
		{id: 'immersiveengineering:crafting/raw_hammercrushing_platinum'},
		{id: 'immersiveengineering:crafting/raw_hammercrushing_zinc'},
		{id: 'immersiveengineering:crafting/hammercrushing_zinc'},
		{id: 'immersiveengineering:crafting/stick_aluminum'},
		{id: 'immersiveengineering:crafting/stick_iron'},
		{id: 'immersiveengineering:crafting/stick_steel'},
		{id: 'immersiveengineering:crafting/string'},
		{id: 'immersiveengineering:crafting/treated_wood_horizontal_from_packaged'},
		{id: 'immersiveengineering:crusher/gravel'},
		{id: 'immersiveengineering:fermenter/apple'},
		{id: 'immersiveengineering:fermenter/beetroot'},
		{id: 'immersiveengineering:fermenter/glow_berries'},
		{id: 'immersiveengineering:fermenter/honey'},
		{id: 'immersiveengineering:fermenter/melon_slice'},
		{id: 'immersiveengineering:fermenter/potato'},
		{id: 'immersiveengineering:fermenter/sugar_cane'},
		{id: 'immersiveengineering:fermenter/sweet_berries'},
		{id: 'immersiveengineering:mixer/herbicide'},
		{id: 'immersiveengineering:smelting/ingot_nickel_from_blasting'},
		{id: 'immersiveengineering:smelting/ingot_nickel_from_blasting2'},
		{id: 'immersiveengineering:smelting/ingot_nickel_from_blasting3'},
		{id: 'immersiveengineering:smelting/ingot_nickel_from_dust_from_blasting'},
		{id: 'immersiveengineering:smelting/ingot_silver_from_blasting'},
		{id: 'immersiveengineering:smelting/ingot_silver_from_blasting2'},
		{id: 'immersiveengineering:smelting/ingot_silver_from_blasting3'},
		{id: 'immersiveengineering:smelting/ingot_silver_from_dust_from_blasting'},
		{id: 'immersiveengineering:smelting/ingot_steel_from_dust_from_blasting'},
		{id: 'immersiveengineering:squeezer/beetroot_seeds'},
		{id: 'immersiveengineering:squeezer/graphite_dust'},
		{id: 'immersiveengineering:squeezer/hemp_seeds'},
		{id: 'immersiveengineering:squeezer/melon_seeds'},
		{id: 'immersiveengineering:squeezer/pumpkin_seeds'},
		{id: 'immersiveengineering:squeezer/wheat_seeds'},

		{id: 'immersivegeology:blasting/blast_crushed_ore_cassiterite_to_ingot'},

		{id: 'lithiccoinstrading:compat/create/sandpaper'},

		//{id: 'immersivepetroleum:ersatz_leather'},
		//{id: 'immersivepetroleum:petcoke_block_to_items'},
		//{id: 'immersivepetroleum:petcoke_items_to_block'},

		{id: 'mcwbridges:bridge_torch'},

		{id: 'mekanism:atomic_disassembler'},
		{id: 'mekanism:energized_smelter'},
		{id: 'mekanism:enriching/charcoal'},
		{id: 'mekanism:factory/advanced/sawing'},
		{id: 'mekanism:factory/advanced/smelting'},
		{id: 'mekanism:factory/basic/sawing'},
		{id: 'mekanism:factory/basic/smelting'},
		{id: 'mekanism:factory/elite/sawing'},
		{id: 'mekanism:factory/elite/smelting'},
		{id: 'mekanism:factory/ultimate/sawing'},
		{id: 'mekanism:factory/ultimate/smelting'},
		{id: 'mekanism:infusion_conversion/carbon/from_charcoal_block'},
		{id: 'mekanism:infusion_conversion/carbon/from_charcoal'},
		{id: 'mekanism:infusion_conversion/carbon/from_enriched'},
		{id: 'mekanism:paper'},
		{id: 'mekanism:rails'},
		{id: 'mekanism:reaction/wood_gasification/logs'},
		{id: 'mekanism:sawing/item_frame'},
		{id: 'mekanism:upgrade/anchor'},

		{id: 'pnaumaticcraft:copper_nugget'},
		{id: 'pneumaticcraft:explosion_crafting/compressed_iron_block'},
		{id: 'pneumaticcraft:explosion_crafting/wheat_flour'},
		{id: 'pneumaticcraft:paper_from_tag_filter'},
		{id: 'pneumaticcraft:pressure_chamber/milk_to_slime_balls'},
		{id: 'pneumaticcraft:pressure_chamber/wheat_flour'},
		{id: 'pneumaticcraft:pressure_chamber_glass_x1'},
		{id: 'pneumaticcraft:pressure_chamber_glass_x4'},
		{id: 'pneumaticcraft:pressure_chamber_valve_x1'},
		{id: 'pneumaticcraft:pressure_chamber_valve_x4'},
		{id: 'pneumaticcraft:refinery/oil_2'},
		{id: 'pneumaticcraft:refinery/oil_3'},
		{id: 'pneumaticcraft:refinery/oil_4'},
		{id: 'pneumaticcraft:refinery_output'},
		{id: 'pneumaticcraft:refinery'},
		{id: 'pneumaticcraft:thermo_plant/ethanol_from_apple'},
		{id: 'pneumaticcraft:thermo_plant/ethanol_from_sugar'},
		{id: 'pneumaticcraft:thermo_plant/ethanol_from_melon'},
		{id: 'pneumaticcraft:thermo_plant/ethanol_from_poisonous_potato'},
		{id: 'pneumaticcraft:thermo_plant/ethanol_from_potato'},
		{id: 'pneumaticcraft:thermo_plant/ethanol_from_sweet_berries'},
		{id: 'pneumaticcraft:thermo_plant/gasoline'},
		{id: 'pneumaticcraft:thermo_plant/kerosene'},
		{id: 'pneumaticcraft:thermo_plant/lubricant_from_biodiesel'},
		{id: 'pneumaticcraft:thermo_plant/lubricant_from_diesel'},
		{id: 'pneumaticcraft:thermo_plant/vegetable_oil_from_crops'},

		{id: 'refinedstorage:silicon'},

		{id: 'securitycraft:reinforced_redstone_lamp'},

		{id: 'sewingkit:leather_sheet_from_rabbit_hide'},

		{id: 'tfmg:compacting/plastic_molding'},
		{id: 'tfmg:distillation/crude_oil_no_naphtha'},
		{id: 'tfmg:distillation/naphtha'},
		{id: 'tfmg:filling/liquid_asphalt_bucket'},
		{id: 'tfmg:filling/liquid_concrete_bucket'},
		{id: 'tfmg:fractional_distillation/crude_oil'},
		{id: 'tfmg:fractional_distillation/crude_oil_sus'},
		{id: 'tfmg:mixing/sulfuric_acid'},
		{id: 'tfmg:mixing/napalm'},
		{id: 'tfmg:mixing/liquid_plastic_from_propylene'},
		{id: 'tfmg:mixing/liquid_plastic_from_ethylene'},
		{id: 'tfmg:crafting/pipes/plastic_pipe_horizontal'},
		{id: 'tfmg:crafting/napalm_bomb'},
		{id: 'tfmg:crafting/napalm_bomb_plastic'},
		{id: 'tfmg:compacting/bitumen'},
		{id: 'tfmg:crafting/epic_party_light_bulb'},
		{id: 'tfmg:crafting/glass_cable_connector'},
		
		{id: 'thinair:soulfire_bottle_from_glass'},	

		{id: 'tfmg:colored_concrete/full_block/red_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/blue_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/black_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/orange_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/magenta_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/light_gray_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/light_blue_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/purple_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/pink_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/green_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/white_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/gray_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/yellow_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/lime_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/cyan_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/pink_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/brown_concrete_q'},
		{id: 'tfmg:colored_concrete/full_block/pink_concrete_q'},
		{id: 'tfmg:mixing/liquid_concrete_'},
		{id: 'tfmg:mixing/liquid_concrete_from_slag'},
		
		{id: 'twilightforest:equipment/fiery_boots'},
		{id: 'twilightforest:equipment/fiery_chestplate'},
		{id: 'twilightforest:equipment/fiery_helmet'},
		{id: 'twilightforest:equipment/fiery_leggings'},
		{id: 'twilightforest:equipment/fiery_pickaxe'},
		{id: 'twilightforest:equipment/fiery_sword'},

		{id: 'untamedwilds:items/arrow_from_shark_teeth'},
		{id: 'untamedwilds:items/food_soup_turtle'},
		{id: 'untamedwilds:items/food_stew_hemlock'},
		//{id: 'untamedwilds:smelting/cooked_bear_meat_campfire'},
		//{id: 'untamedwilds:smelting/cooked_bear_meat'},
		//{id: 'untamedwilds:smelting/cooked_pachyderm_meat_campfire'},
		//{id: 'untamedwilds:smelting/cooked_pachyderm_meat'},
		//{id: 'untamedwilds:smelting/cooked_turtle_meat_campfire'},
		//{id: 'untamedwilds:smelting/cooked_turtle_meat'},

		{id: 'waterflasks:leather_knapping/leather_side'},
	])
})