
#This config option allows you to add custom wood types for Totem Bases and Totem Poles.
#Must be a list of tables with the following keys:
#  id: Required: The wood type's ID. Must be a valid resource location (Example: "my_mod:my_wood_type").
#  logs: Required: Specifies which log blocks are recognized as belonging to this wood type by the Totem Whittling Knife.
#        Currently, only block tags are supported. Must be a string starting with '#' specifying a valid block tag
#        (Example: "#minecraft:crimson_stems").
#  woodColor: Optional: An integer between 0 and 61 specifying the map color of the wood's inside.
#             See https://minecraft.wiki/w/Map_item_format#Color_table for a list of possible colors. Defaults to 13
#             (Oak Log's wood color).
#  barkColor: Optional: An integer between 0 and 61 specifying the map color of the wood's bark, see above. Defaults
#             to 34 (Oak Log's bark color).
#
#Textures and language keys for the corresponding Totem Pole/Base blocks need to be added via a resource pack.
#See here for an example resource pack: https://github.com/TeamTotemic/Totemic/tree/1.20.1/CustomWoodTypeTestResources
#
#Please note that issues will arise if the wood types are not the same on the server and client.
#
#Example entry:
#[[customTotemWoodTypes]]
#    id = "my_mod:crimson"
#    logs = "#minecraft:crimson_stems"
#    woodColor = 53  #optional
#    barkColor = 54  #optional
[[customTotemWoodTypes]]
	id = "beneath:wood/log/crimson"
	logs = "#tfc:crimson_logs"
	woodColor = 53
	barkColor = 54

[[customTotemWoodTypes]]
	id = "beneath:wood/log/warped"
	logs = "#tfc:warped_logs"
	woodColor = 55
	barkColor = 56

[[customTotemWoodTypes]]
	id = "tfc:wood/log/acacia"
	logs = "#tfc:acacia_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/ash"
	logs = "#tfc:ash_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/aspen"
	logs = "#tfc:aspen_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/birch"
	logs = "#tfc:birch_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/blackwood"
	logs = "#tfc:blackwood_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/chestnut"
	logs = "#tfc:chestnut_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/douglas_fir"
	logs = "#tfc:douglas_fir_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/hickory"
	logs = "#tfc:hickory_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/kapok"
	logs = "#tfc:kapok_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/mangrove"
	logs = "#tfc:mangrove_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/maple"
	logs = "#tfc:maple_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/oak"
	logs = "#tfc:oak_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/palm"
	logs = "#tfc:palm_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/pine"
	logs = "#tfc:pine_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/rosewood"
	logs = "#tfc:rosewood_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/sequoia"
	logs = "#tfc:sequoia_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/spruce"
	logs = "#tfc:spruce_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/sycamore"
	logs = "#tfc:sycamore_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/white_cedar"
	logs = "#tfc:white_cedar_logs"

[[customTotemWoodTypes]]
	id = "tfc:wood/log/willow"
	logs = "#tfc:willow_logs"

